name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
    steps:
      - name: Now it is
        run: |
          echo date
    steps:
      - name: Directory content
        run: |
          echo ls -l